// Categories
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

// Comments
export const FETCH_COMMENTS_BY_POST_REQUEST = 'FETCH_COMMENTS_BY_POST_REQUEST';
export const FETCH_COMMENTS_BY_POST_SUCCESS = 'FETCH_COMMENTS_BY_POST_SUCCESS';

export const FETCH_COMMENT_BY_ID_REQUEST = 'FETCH_COMMENT_BY_ID_REQUEST';
export const FETCH_COMMENT_BY_ID_SUCCESS = 'FETCH_COMMENT_BY_ID_SUCCESS';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';

export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';

export const INCREMENT_COMMENT_SCORE_REQUEST = 'INCREMENT_COMMENT_SCORE_REQUEST';
export const INCREMENT_COMMENT_SCORE_SUCCESS = 'INCREMENT_COMMENT_SCORE_SUCCESS';

export const DECREMENT_COMMENT_SCORE_REQUEST = 'DECREMENT_COMMENT_SCORE_REQUEST';
export const DECREMENT_COMMENT_SCORE_SUCCESS = 'DECREMENT_COMMENT_SCORE_SUCCESS';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';

// Posts
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';

export const INCREMENT_POST_SCORE_REQUEST = 'INCREMENT_POST_SCORE_REQUEST';
export const INCREMENT_POST_SCORE_SUCCESS = 'INCREMENT_POST_SCORE_SUCCESS';

export const DECREMENT_POST_SCORE_REQUEST = 'DECREMENT_POST_SCORE_REQUEST';
export const DECREMENT_POST_SCORE_SUCCESS = 'DECREMENT_POST_SCORE_SUCCESS';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';

// Sort
export const SORT_BY_VOTE_SCORE = 'SORT_BY_VOTE_SCORE';
export const SORT_BY_TIMESTAMP = 'SORT_BY_TIMESTAMP';
